package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sovrn-tech/sovren-exchange-integration/go/client"
)

// sharedGatewayMarker must appear in a manifest whose endpoints do not span
// two distinct providers (contract rule 5 documented-note requirement).
const sharedGatewayMarker = "NOTE(shared-gateway)"

const sharedGatewayNote = `  # ` + sharedGatewayMarker + `: both Sovren bootstrap endpoints are fronted by the
  # same gateway today; exchange-run nodes are the mandated redundancy path for
  # custody-critical operations (FR-006/FR-013). An infrastructure-independent
  # second provider entry is added when plan D12 lands.`

// renderManifestYAML renders network.yaml with the contract's key order.
// client.ParseManifest decodes with KnownFields(true), so the shared-gateway
// note is a comment, not a key.
func renderManifestYAML(m *client.NetworkManifest) []byte {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Sovren network manifest — contracts/network-manifest.md, schema_version %d.", m.SchemaVersion)
	w("# Generated by sovren-manifest; regenerate instead of editing by hand.")
	w("schema_version: %d", m.SchemaVersion)
	w("network_name: %s", m.NetworkName)
	w("network_type: %s", m.NetworkType)
	w("chain_id: %s", m.ChainID)
	w("daemon_name: %s", m.DaemonName)
	w("node_home: %s", m.NodeHome)
	w("account_prefix: %s", m.AccountPrefix)
	w("validator_operator_prefix: %s", m.ValidatorOperatorPrefix)
	w("validator_consensus_prefix: %s", m.ValidatorConsensusPrefix)
	w("base_denom: %s", m.BaseDenom)
	w("display_denom: %s", m.DisplayDenom)
	w("display_exponent: %d", m.DisplayExponent)
	w("symbol: %s", m.Symbol)
	w("account_key_algorithm: %s", m.AccountKeyAlgorithm)
	w("consensus_key_algorithm: %s", m.ConsensusKeyAlgorithm)
	w("slip44_coin_type: %d", m.Slip44CoinType)
	w("versions:")
	w("  # sdk/app verified against live REST node_info; cometbft/ibc_go/cosmwasm/go")
	w("  # pinned from the release go.mod (rule 2 — the live CometBFT line version")
	w("  # may lag within the same minor line; skew is recorded, never hidden).")
	w("  sdk: %s", m.Versions.SDK)
	w("  cometbft: %s", m.Versions.CometBFT)
	w("  ibc_go: %s", m.Versions.IBCGo)
	w("  cosmwasm_wasmd: %s", m.Versions.CosmwasmWasmd)
	w("  go: %q", m.Versions.Go)
	w("  app: %s", m.Versions.App)
	w("fees:")
	w("  # minimum_gas_price mirrors the live x/globalfee floor (rule 3).")
	w("  minimum_gas_price: %q", m.Fees.MinimumGasPrice)
	w("  recommended_gas_price: %q", m.Fees.RecommendedGasPrice)
	w("  recommended_gas_adjustment: %q", m.Fees.RecommendedGasAdjustment)
	w("ports: { p2p: %d, rpc: %d, grpc: %d, rest: %d, metrics: %d }",
		m.Ports.P2P, m.Ports.RPC, m.Ports.GRPC, m.Ports.REST, m.Ports.Metrics)
	w("genesis:")
	w("  sha256: %s", m.Genesis.SHA256)
	w("  # genesis file injected next to this manifest at export.")
	w("  file: %s", m.Genesis.File)
	w("endpoints:")
	if distinctProviders(m.Endpoints) < 2 {
		b.WriteString(sharedGatewayNote + "\n")
	}
	for _, ep := range m.Endpoints {
		w("  - { kind: %s, url: %q, provider: %s }", ep.Kind, ep.URL, ep.Provider)
	}
	w("peers:")
	w("  # DNS names only — raw IPs forbidden on both networks (rule 6).")
	w("  seeds:")
	for _, s := range m.Peers.Seeds {
		w("    - %q", s)
	}
	w("  persistent_peers:")
	for _, p := range m.Peers.PersistentPeers {
		w("    - %q", p)
	}
	w("links:")
	w("  explorer: %q", m.Links.Explorer)
	w("  faucet: %s", nullableLink(m.Links.Faucet))
	w("  status_page: %s", nullableLink(m.Links.StatusPage))
	w("  registry_dir: %s", m.Links.RegistryDir)
	if m.NetworkType == "testnet" {
		w("divergences:")
		for _, d := range m.Divergences {
			w("  - %q", d)
		}
	} else {
		w("divergences: []")
	}
	return b.Bytes()
}

func nullableLink(v *string) string {
	if v == nil {
		return "null"
	}
	return fmt.Sprintf("%q", *v)
}

func distinctProviders(eps []client.ManifestEndpoint) int {
	seen := map[string]bool{}
	for _, ep := range eps {
		seen[ep.Provider] = true
	}
	return len(seen)
}

// Sidecars are generated FROM the manifest and byte-verified at rule 10; the
// manifest is the single source of truth.

func renderGenesisSHA256(m *client.NetworkManifest) []byte {
	return []byte(fmt.Sprintf("%s  %s\n", m.Genesis.SHA256, m.Genesis.File))
}

func renderPeersTxt(m *client.NetworkManifest) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated from network.yaml by sovren-manifest; do not edit.\n")
	fmt.Fprintf(&b, "SEEDS=%s\n", strings.Join(m.Peers.Seeds, ","))
	fmt.Fprintf(&b, "PERSISTENT_PEERS=%s\n", strings.Join(m.Peers.PersistentPeers, ","))
	return b.Bytes()
}

type endpointJSON struct {
	Kind     string `json:"kind"`
	URL      string `json:"url"`
	Provider string `json:"provider"`
}

type endpointsSidecar struct {
	ChainID   string         `json:"chain_id"`
	Endpoints []endpointJSON `json:"endpoints"`
	Explorer  string         `json:"explorer"`
}

func renderEndpointsJSON(m *client.NetworkManifest) ([]byte, error) {
	eps := make([]endpointJSON, 0, len(m.Endpoints))
	for _, ep := range m.Endpoints {
		eps = append(eps, endpointJSON{Kind: ep.Kind, URL: ep.URL, Provider: ep.Provider})
	}
	out, err := json.MarshalIndent(endpointsSidecar{
		ChainID:   m.ChainID,
		Endpoints: eps,
		Explorer:  m.Links.Explorer,
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}
