package main

// Markdown renderer for the FR-058 certification report template.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var groupTitles = map[string]string{
	"N": "Network & node",
	"A": "Address & amounts",
	"D": "Deposits",
	"R": "Restart / durability",
	"W": "Withdrawals",
	"S": "Sweeps",
	"C": "Reconciliation & operations",
	"M": "Monitoring",
	"G": "Go-live & operational readiness",
}

var groupOrder = []string{"N", "A", "D", "R", "W", "S", "C", "M", "G"}

func renderMarkdown(r *Report) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Sovren Technical Integration Certification Report\n\n")
	w("> **Scope — technical integration only.** This certifies that the exchange's\n")
	w("> integration correctly implements the native SOVR technical behaviors\n")
	w("> exercised below (node sync/failover, chain-ID/network config, sovr1 address\n")
	w("> generation, deposit detection, failed-tx rejection, duplicate-credit and\n")
	w("> duplicate-withdrawal prevention, withdrawal construction/signing, sequence\n")
	w("> management/recovery, sweep/fee handling, scanner-restart recovery, balance\n")
	w("> reconciliation, and a controlled testnet round trip, plus offline\n")
	w("> validation of the shipped mainnet network manifest). It does **NOT**\n")
	w("> certify the exchange's AML/sanctions program, legal or regulatory\n")
	w("> compliance, cybersecurity controls, private-key management, custody policy,\n")
	w("> solvency or insurance, customer ledger, or withdrawal-limit/fraud controls —\n")
	w("> those remain the exchange's sole responsibility.\n\n")
	if !r.Environment.Certifying {
		w("> **NON-CERTIFYING RUN** — environment mode `%s`. A certification report is only\n", r.Environment.Mode)
		w("> valid from `--network testnet` (contracts/certification.md).\n\n")
	}

	w("| Field | Value |\n|---|---|\n")
	w("| Exchange | %s |\n", orFill(r.Exchange))
	w("| Operator | %s |\n", orFill(r.Operator))
	w("| Network (chain_id) | %s |\n", orDash(r.Network))
	w("| Environment mode | %s |\n", r.Environment.Mode)
	w("| Kit version | %s |\n", orDash(r.KitVersion))
	w("| Adapter version | %s |\n", orDash(r.AdapterVersion))
	w("| Storage backend | %s |\n", orDash(r.StorageBackend))
	w("| Started | %s |\n", orDash(r.StartedAt))
	w("| Completed | %s |\n", orDash(r.CompletedAt))
	w("\n")

	w("## Environment\n\n")
	if len(r.Environment.Endpoints) > 0 {
		w("Endpoints used: %s\n\n", strings.Join(r.Environment.Endpoints, ", "))
	}
	if len(r.Environment.NodeVersions) > 0 {
		w("| Component | Version |\n|---|---|\n")
		for _, k := range sortedKeys(r.Environment.NodeVersions) {
			w("| %s | %s |\n", k, r.Environment.NodeVersions[k])
		}
		w("\n")
	}
	if len(r.Environment.Toolchain) > 0 {
		w("Toolchain: ")
		var parts []string
		for _, k := range sortedKeys(r.Environment.Toolchain) {
			parts = append(parts, fmt.Sprintf("%s %s", k, r.Environment.Toolchain[k]))
		}
		w("%s\n\n", strings.Join(parts, "; "))
	}

	w("## Summary\n\n")
	s := r.Summary
	w("| Total | PASS | FAIL | SKIPPED | BLOCKED | Required skipped |\n|---|---|---|---|---|---|\n")
	w("| %d | %d | %d | %d | %d | %d |\n\n", s.Total, s.Pass, s.Fail, s.Skipped, s.Blocked, s.RequiredSkipped)
	w("**Overall verdict: %s**", s.Overall)
	if !r.Environment.Certifying {
		w(" _(non-certifying local run)_")
	}
	w("\n\n")
	if s.Blocked > 0 {
		w("%d scenario(s) are BLOCKED on unmet external dependencies. BLOCKED results do\n", s.Blocked)
		w("not fail a run, but a GA certification requires zero BLOCKED scenarios.\n\n")
	}
	w("GA-ready: **%v**\n\n", s.GAReady)

	byGroup := map[string][]ScenarioResult{}
	for _, sc := range r.Scenarios {
		byGroup[sc.Group] = append(byGroup[sc.Group], sc)
	}
	order := append([]string{}, groupOrder...)
	for g := range byGroup {
		if groupTitles[g] == "" {
			order = append(order, g)
		}
	}
	for _, g := range order {
		scs := byGroup[g]
		if len(scs) == 0 {
			continue
		}
		title := groupTitles[g]
		if title == "" {
			title = g
		}
		w("## Group %s — %s\n\n", g, title)
		w("| ID | Scenario | Result | Requirements | Detail |\n|---|---|---|---|---|\n")
		for _, sc := range scs {
			res := sc.Result
			if sc.Result == string(StatusBlocked) && sc.Dependency != "" {
				res = fmt.Sprintf("BLOCKED(%s)", sc.Dependency)
			}
			w("| %s | %s | %s | %s | %s |\n",
				sc.ID, mdEscape(sc.Title), res,
				strings.Join(sc.RequirementRefs, ", "),
				mdEscape(detailFor(sc)))
		}
		w("\n")
	}

	w("---\n\nGenerated by `sovren-cert` from `certification.json` (data model §13).\n")
	return b.String()
}

// detailFor renders the reason or a compact evidence digest.
func detailFor(sc ScenarioResult) string {
	if sc.Reason != "" {
		return truncate(sc.Reason, 300)
	}
	if len(sc.Evidence) == 0 {
		return ""
	}
	var parts []string
	for _, k := range sortedAnyKeys(sc.Evidence) {
		v := fmt.Sprintf("%v", sc.Evidence[k])
		parts = append(parts, fmt.Sprintf("%s=%s", k, truncate(v, 80)))
		if len(parts) >= 6 {
			parts = append(parts, "…")
			break
		}
	}
	return truncate(strings.Join(parts, "; "), 400)
}

func renderToFile(dir string) error {
	r, err := readReport(dir)
	if err != nil {
		return err
	}
	md := renderMarkdown(r)
	return os.WriteFile(filepath.Join(dir, reportMarkdownName), []byte(md), 0o644)
}

func orFill(s string) string {
	if s == "" {
		return "_(fill in)_"
	}
	return s
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedAnyKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
